version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "FreshTracks"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12o3g3x0szjnk"
s3_prefix = "FreshTracks"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ValidateEmail=\"test@email.com\""

