version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "FreshTracks"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1x1478kiglkw9"
s3_prefix = "FreshTracks"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Auth0EventBusName=\"default\" Auth0Domain=\"bls20.auth0.com\" Auth0Audience=\"https://myfreshtracks.com\" Auth0ClientId=\"QP19oglIMqRDlNoy2kOykclw2lbcxPh8\" ZendeskEventBusName=\"default\" ZenDeskDomain=\"example-domain.zendesk\" ZenDeskPassword=\"abcfedghijllmnop12345678\" ZenDeskUsername=\"email@address.com\""

